In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'C:\Users\JDD\Desktop\加权平均分组.csv')

In [3]:
df

,auther,ctr,action,score,group,ctr2,action2,score2,group2
0,2697826,0.116665,0.008101,0.103637,C,0.098854,0.008196,0.087975,B
1,3050899,0.106128,0.006047,0.094118,C,0.093032,0.007378,0.082753,C
2,1878235,0.105865,0.007311,0.094039,C,0.179800,0.005092,0.158835,A
3,1415412,0.099695,0.006526,0.088514,D,0.096336,0.009404,0.085904,C
4,3235258,0.127751,0.005226,0.113048,C,0.100318,0.009742,0.089449,B
...,...,...,...,...,...,...,...,...,...
2831,1764006,0.077922,0.005647,0.069249,D,0.070673,0.006122,0.062927,D
2832,1191612,0.154884,0.011163,0.137637,A,0.119495,0.017512,0.107257,A
2833,2571005,0.172488,0.016386,0.153756,A,0.128423,0.008723,0.114059,A
2834,2257890,0.169807,0.008854,0.150493,A,0.147005,0.009310,0.130481,A
2835,1574251,0.144800,0.011409,0.128793,B,0.108677,0.010242,0.096865,B